import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { PlusCircle, MapPin, CheckCircle2, Zap, Smile, Gift, ShoppingBag, Bot, ChevronDown, ChevronUp } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import Navbar from '../components/Navbar';

const Landing: React.FC = () => {
    const navigate = useNavigate();
    const [resolvedCount, setResolvedCount] = useState<number>(0);
    const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);

    const faqs = [
        { 
            question: "Why do we need waste management?", 
            answer: "Proper waste management is needed to safeguard our environment, protect public health, conserve resources, and promote sustainable economic development. By implementing responsible waste management practices, we can create a cleaner, healthier, and a more sustainable future." 
        },
        { 
            question: "What is waste management in construction?", 
            answer: "Construction waste management involves the handling, recycling, and safe disposal of materials generated during construction, renovation, and demolition. It focuses on reducing waste at the source and maximizing the reuse of materials like concrete, wood, and metals." 
        },
        { 
            question: "What are the 5rs of waste management?", 
            answer: "The 5 R's of waste management are Refuse, Reduce, Reuse, Repurpose, and Recycle. They provide a framework for minimizing waste generation and finding alternative uses for items to divert them from landfills." 
        },
        { 
            question: "How to do a waste management audit?", 
            answer: "A waste audit involves systematically measuring and analyzing the waste generated by a facility. Steps include planning the audit, collecting and sorting waste into categories, weighing each category, analyzing the data, and creating an action plan to improve waste reduction and recycling rates." 
        },
        { 
            question: "What best practices can reduce waste generation at the source in industrial and retail settings?", 
            answer: "Best practices include optimizing inventory management to prevent overstocking, implementing lean manufacturing techniques, redesigning packaging to use less material, and establishing closed-loop systems where waste from one process becomes a resource for another." 
        }
    ];

    useEffect(() => {
        const fetchStats = async () => {
            let localReports = [];
            try {
                localReports = JSON.parse(localStorage.getItem('greenary_reports') || '[]');
            } catch (e) {}

            try {
                const response = await fetch('/api/reports');
                if (response.ok) {
                    const reports = await response.json();
                    
                    const localIds = new Set(reports.map((r: any) => r.id));
                    const missingLocal = localReports.filter((r: any) => !localIds.has(r.id));
                    const allReports = [...reports, ...missingLocal];

                    const resolved = allReports.filter((r: any) => r.status && r.status.toLowerCase() === 'resolved').length;
                    setResolvedCount(resolved);
                } else {
                    const resolved = localReports.filter((r: any) => r.status && r.status.toLowerCase() === 'resolved').length;
                    setResolvedCount(resolved);
                }
            } catch (e) {
                console.log("Backend not available, loading stats from localStorage.");
                const resolved = localReports.filter((r: any) => r.status && r.status.toLowerCase() === 'resolved').length;
                setResolvedCount(resolved);
            }
        };

        fetchStats();
        window.addEventListener('reportAdded', fetchStats);
        return () => {
            window.removeEventListener('reportAdded', fetchStats);
        };
    }, []);

    return (
        <div className="min-h-screen bg-[#F8F9FA] font-sans text-slate-900 selection:bg-brand-200">
            <Navbar />

            {/* Hero Section */}
            <section className="relative pt-20 mt-1 pb-32 flex items-center justify-start min-h-[600px] overflow-hidden">
                {/* Background Image */}
                <div
                    className="absolute inset-0 z-0 bg-cover bg-center bg-no-repeat w-full h-full"
                    style={{
                        backgroundImage: `url('https://images.unsplash.com/photo-1501696461441-8a1f7c4c9f7b')`, // City park style
                    }}
                >
                    <div className="absolute inset-0 bg-gradient-to-r from-green-950/95 via-green-900/80 to-transparent"></div>
                </div>

                <div className="relative z-10 max-w-7xl mx-auto px-8 w-full">
                    <div className="max-w-2xl text-left">
                        <motion.h1
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8 }}
                            className="text-5xl md:text-6xl font-extrabold text-white leading-[1.1] tracking-tight mb-6"
                        >
                            Keep Our City<br />Clean and<br />Sustainable
                        </motion.h1>
                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8, delay: 0.2 }}
                            className="text-lg text-green-50 mb-10 leading-relaxed max-w-xl"
                        >
                            Together, we can maintain the beauty of our community. Report local waste issues and track their resolution in real-time.
                        </motion.p>

                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8, delay: 0.4 }}
                            className="flex flex-col sm:flex-row gap-4"
                        >
                            <Link
                                to="/report"
                                className="inline-flex items-center justify-center gap-2 bg-green-950/40 hover:bg-green-900/60 backdrop-blur-md text-white px-8 py-4 rounded-xl font-medium transition-all group border border-green-800/30 shadow-lg"
                            >
                                <PlusCircle className="w-5 h-5 text-white/80 group-hover:text-white transition-colors" />
                                Report an Issue
                            </Link>
                            <Link
                                to="/issues"
                                className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 backdrop-blur-md text-white px-8 py-4 rounded-xl font-medium transition-all group border border-white/20 shadow-lg"
                            >
                                <MapPin className="w-5 h-5 text-white/80 group-hover:text-white transition-colors" />
                                Track Your Request
                            </Link>
                        </motion.div>
                    </div>
                </div>
            </section>

            {/* Statistics Section */}
            <section className="relative z-20 -mt-16 max-w-7xl mx-auto px-8 w-full">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 lg:gap-10">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        onClick={() => navigate('/issues', { state: { filter: 'Resolved' } })}
                        className="bg-white rounded-3xl p-8 flex flex-col items-center text-center shadow-[0_8px_30px_rgb(0,0,0,0.04)] transition-all hover:shadow-xl hover:-translate-y-1 cursor-pointer"
                    >
                        <div className="w-16 h-16 rounded-full bg-emerald-100/50 flex items-center justify-center mb-6">
                            <CheckCircle2 className="w-8 h-8 text-emerald-600" />
                        </div>
                        <h3 className="text-4xl font-extrabold text-slate-900 mb-2">
                            {resolvedCount}
                        </h3>
                        <p className="text-sm font-medium text-slate-500">Requests Resolved</p>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.1 }}
                        className="bg-white rounded-3xl p-8 flex flex-col items-center text-center shadow-[0_8px_30px_rgb(0,0,0,0.04)] transition-transform hover:-translate-y-1"
                    >
                        <div className="w-16 h-16 rounded-full bg-blue-100/50 flex items-center justify-center mb-6">
                            <Zap className="w-8 h-8 text-blue-500 fill-blue-500/20" />
                        </div>
                        <h3 className="text-4xl font-extrabold text-slate-900 mb-2">24hr</h3>
                        <p className="text-sm font-medium text-slate-500">Average Response Time</p>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.2 }}
                        className="bg-white rounded-3xl p-8 flex flex-col items-center text-center shadow-[0_8px_30px_rgb(0,0,0,0.04)] transition-transform hover:-translate-y-1"
                    >
                        <div className="w-16 h-16 rounded-full bg-orange-100/50 flex items-center justify-center mb-6">
                            <Smile className="w-8 h-8 text-orange-500" />
                        </div>
                        <h3 className="text-4xl font-extrabold text-slate-900 mb-2">95%</h3>
                        <p className="text-sm font-medium text-slate-500">Community Satisfaction</p>
                    </motion.div>
                </div>
            </section>

            {/* How It Works Section */}
            <section className="py-24 max-w-7xl mx-auto px-8 w-full text-center">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="mb-16"
                >
                    <span className="inline-block px-4 py-1.5 rounded-full bg-blue-100 text-blue-600 text-xs font-bold tracking-widest uppercase mb-4">Features</span>
                    <h2 className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-6">Explore Greenary</h2>
                </motion.div>

                <div className="flex flex-col gap-20 relative max-w-5xl mx-auto mt-12">
                    {/* Central Line */}
                    <div className="hidden md:block absolute left-1/2 top-0 bottom-0 w-0.5 bg-gradient-to-b from-emerald-100 via-emerald-200 to-transparent -translate-x-1/2"></div>

                    {/* Step 1 */}
                    <motion.div 
                        initial={{ opacity: 0, y: 40 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-100px" }}
                        className="flex flex-col md:flex-row items-center gap-10 md:gap-20 group cursor-pointer"
                        onClick={() => navigate('/dashboard')}
                    >
                        {/* Text Left */}
                        <div className="flex-1 md:text-right order-2 md:order-1">
                            <div className="text-emerald-500 font-extrabold tracking-widest text-xs uppercase mb-3">Feature 01</div>
                            <h3 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4 group-hover:text-emerald-700 transition-colors">Earn Reward Points</h3>
                            <p className="text-slate-500 leading-relaxed md:ml-auto max-w-sm">
                                Get rewarded for your environmental contributions! Earn green points for every successful waste report and community cleanup effort you participate in.
                            </p>
                        </div>
                        
                        {/* Center Node */}
                        <div className="hidden md:flex w-16 h-16 rounded-full bg-white border-4 border-emerald-100 items-center justify-center font-bold text-2xl text-emerald-600 shrink-0 z-10 shadow-lg group-hover:bg-emerald-500 group-hover:text-white group-hover:border-emerald-200 transition-all duration-300 order-2">
                            1
                        </div>

                        {/* Visual Right */}
                        <div className="flex-1 w-full order-1 md:order-3">
                            <div className="bg-[#1f4c3a] rounded-[2rem] p-10 flex items-center justify-center aspect-video shadow-xl group-hover:shadow-2xl group-hover:-translate-y-2 transition-all duration-300 relative overflow-hidden">
                                <div className="absolute inset-0 bg-gradient-to-br from-emerald-400/20 to-transparent"></div>
                                <Gift className="w-24 h-24 text-emerald-400/50 group-hover:scale-110 group-hover:text-emerald-300 transition-all duration-500 relative z-10" strokeWidth={1} />
                            </div>
                        </div>
                    </motion.div>

                    {/* Step 2 */}
                    <motion.div 
                        initial={{ opacity: 0, y: 40 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-100px" }}
                        className="flex flex-col md:flex-row items-center gap-10 md:gap-20 group cursor-pointer"
                        onClick={() => navigate('/shop')}
                    >
                        {/* Visual Left */}
                        <div className="flex-1 w-full order-1">
                            <div className="bg-blue-50 rounded-[2rem] p-10 flex items-center justify-center aspect-video shadow-xl group-hover:shadow-2xl group-hover:-translate-y-2 transition-all duration-300 relative overflow-hidden border border-blue-100">
                                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-[0.03]"></div>
                                <div className="w-20 h-20 bg-white rounded-full flex items-center justify-center shadow-lg relative z-10">
                                    <ShoppingBag className="w-10 h-10 text-blue-600" />
                                </div>
                                <div className="absolute w-32 h-32 border border-blue-200 rounded-full animate-ping opacity-20"></div>
                            </div>
                        </div>

                        {/* Center Node */}
                        <div className="hidden md:flex w-16 h-16 rounded-full bg-white border-4 border-blue-100 items-center justify-center font-bold text-2xl text-blue-600 shrink-0 z-10 shadow-lg group-hover:bg-blue-600 group-hover:text-white group-hover:border-blue-200 transition-all duration-300 order-2">
                            2
                        </div>

                        {/* Text Right */}
                        <div className="flex-1 order-2 md:order-3">
                            <div className="text-blue-600 font-extrabold tracking-widest text-xs uppercase mb-3">Feature 02</div>
                            <h3 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4 group-hover:text-blue-700 transition-colors">Shop Eco-Friendly</h3>
                            <p className="text-slate-500 leading-relaxed max-w-sm">
                                Visit the Green Shop to redeem your hard-earned points! Purchase sustainable, eco-friendly products and actively support a greener lifestyle.
                            </p>
                        </div>
                    </motion.div>

                    {/* Step 3 */}
                    <motion.div 
                        initial={{ opacity: 0, y: 40 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-100px" }}
                        className="flex flex-col md:flex-row items-center gap-10 md:gap-20 group cursor-pointer"
                        onClick={() => window.dispatchEvent(new CustomEvent('openChatbot'))}
                    >
                        {/* Text Left */}
                        <div className="flex-1 md:text-right order-2 md:order-1">
                            <div className="text-amber-500 font-extrabold tracking-widest text-xs uppercase mb-3">Feature 03</div>
                            <h3 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4 group-hover:text-amber-600 transition-colors">AI Chatbot Assistant</h3>
                            <p className="text-slate-500 leading-relaxed md:ml-auto max-w-sm">
                                Have questions about recycling or waste segregation? Our 24/7 smart AI Chatbot provides instant guidance on all your waste management queries.
                            </p>
                        </div>
                        
                        {/* Center Node */}
                        <div className="hidden md:flex w-16 h-16 rounded-full bg-white border-4 border-amber-100 items-center justify-center font-bold text-2xl text-amber-500 shrink-0 z-10 shadow-lg group-hover:bg-amber-400 group-hover:text-white group-hover:border-amber-200 transition-all duration-300 order-2">
                            3
                        </div>

                        {/* Visual Right */}
                        <div className="flex-1 w-full order-1 md:order-3">
                            <div className="bg-slate-900 rounded-[2rem] p-10 flex items-center justify-center aspect-video shadow-xl group-hover:shadow-2xl group-hover:-translate-y-2 transition-all duration-300 relative overflow-hidden">
                                <Bot className="w-24 h-24 text-amber-400 opacity-50 group-hover:opacity-100 group-hover:rotate-12 transition-all duration-500 relative z-10" strokeWidth={1} />
                            </div>
                        </div>
                    </motion.div>

                </div>
            </section>

            {/* FAQ Section */}
            <section className="py-24 max-w-4xl mx-auto px-8 w-full">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="mb-12"
                >
                    <h2 className="text-4xl md:text-5xl font-extrabold text-[#1a202c] mb-6 tracking-tight">FAQs About Waste Management<br/>System</h2>
                </motion.div>

                <div className="space-y-4">
                    {faqs.map((faq, index) => (
                        <motion.div 
                            key={index}
                            initial={{ opacity: 0, y: 10 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: index * 0.1 }}
                            className="border border-[#cbd5e1] rounded-2xl overflow-hidden bg-white shadow-sm"
                        >
                            <button
                                onClick={() => setOpenFaqIndex(openFaqIndex === index ? null : index)}
                                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-slate-50 transition-colors"
                            >
                                <span className="font-bold text-[#1e293b] pr-8 text-[15px]">{faq.question}</span>
                                {openFaqIndex === index ? (
                                    <ChevronUp className="w-5 h-5 text-slate-700 flex-shrink-0" strokeWidth={2.5} />
                                ) : (
                                    <ChevronDown className="w-5 h-5 text-slate-700 flex-shrink-0" strokeWidth={2.5} />
                                )}
                            </button>
                            
                            <AnimatePresence>
                                {openFaqIndex === index && (
                                    <motion.div
                                        initial={{ height: 0, opacity: 0 }}
                                        animate={{ height: "auto", opacity: 1 }}
                                        exit={{ height: 0, opacity: 0 }}
                                        transition={{ duration: 0.2 }}
                                    >
                                        <div className="px-6 pb-6 text-[#475569] leading-[1.6] text-[15px]">
                                            {faq.answer}
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>
                        </motion.div>
                    ))}
                </div>
            </section>

            {/* Footer */}
            <footer className="border-t border-slate-200 bg-transparent py-16">
                <div className="max-w-7xl mx-auto px-8 w-full flex flex-col md:flex-row justify-between gap-10">
                    <div className="max-w-xs">
                        <div className="font-bold text-xl tracking-tight text-slate-900 mb-4">Greenary</div>
                        <p className="text-xs text-slate-500 leading-relaxed mb-8">
                            Empowering citizens to take charge of their urban environment through seamless reporting and transparent resolution tracking.
                        </p>
                        <p className="text-[10px] text-slate-400">
                            © {new Date().getFullYear()} Greenary. All rights reserved.
                        </p>
                    </div>

                    <div className="flex gap-16 text-xs w-full md:w-auto">
                        <div>
                            <h4 className="font-bold text-[10px] uppercase tracking-wider text-slate-900 mb-4">Resources</h4>
                            <ul className="space-y-3 font-medium text-slate-500">
                                <li><Link to="/contact" className="hover:text-slate-900 transition-colors">Contact Support</Link></li>
                                <li><Link to="/privacy" className="hover:text-slate-900 transition-colors">Privacy Policy</Link></li>
                            </ul>
                        </div>
                        <div>
                            <h4 className="font-bold text-[10px] uppercase tracking-wider text-slate-900 mb-4">Legal</h4>
                            <ul className="space-y-3 font-medium text-slate-500">
                                <li><Link to="/terms" className="hover:text-slate-900 transition-colors">Terms of Service</Link></li>
                                <li><Link to="/accessibility" className="hover:text-slate-900 transition-colors">Accessibility</Link></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>

        </div>
    );
};

export default Landing;
